<?php

namespace App\Services\Mutators;

class Number extends MutatorsBase
{
    public static function turn($name, $value = null)
    {
        return parent::turn($name, $value); // TODO: Change the autogenerated stub
    }
}
