<?php

namespace App\Services\Mutators;

class TimeNow extends MutatorsBase
{
    public static function make($name, $value = null)
    {
        $value = now()->toDateTimeString();

        return parent::make($name, $value); // TODO: Change the autogenerated stub
    }
}
